name: backend-deploy-staging (disabled)

on:
  # Disabled to avoid App Service slot costs; kept for history. Manual run only.
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled. Backend deploys go directly to production via main_danstcg-webapp.yml."
