name: frontend-ci

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main, "feature/**" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        working-directory: frontend
        run: npm ci || npm install

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Run tests (if any)
        working-directory: frontend
        run: |
          npm test --silent || echo "No tests or tests failed; continuing for CI setup"

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
